"""integrations_credentials combined into users_credentials

Revision ID: 1a9320f696c6
Revises: 6cc2a6efd16f
Create Date: 2026-06-10 19:23:01.945044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a9320f696c6'
down_revision: Union[str, Sequence[str], None] = '6cc2a6efd16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrations_credentials_integration_id'), table_name='integrations_credentials')
    op.drop_table('integrations_credentials')
    op.add_column('users_integrations', sa.Column('credentials_type', postgresql.ENUM('OAUTH2', 'API_KEY', name='credentials_type_enum'), nullable=False))
    op.add_column('users_integrations', sa.Column('credentials', sa.TEXT(), nullable=False))
    op.add_column('users_integrations', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_integrations', 'meta')
    op.drop_column('users_integrations', 'credentials')
    op.drop_column('users_integrations', 'credentials_type')
    op.create_table('integrations_credentials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credentials_type', postgresql.ENUM('OAUTH2', 'API_KEY', name='credentials_type_enum'), autoincrement=False, nullable=False),
    sa.Column('credentials', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['users_integrations.id'], name=op.f('integrations_credentials_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('integrations_credentials_pkey'))
    )
    op.create_index(op.f('ix_integrations_credentials_integration_id'), 'integrations_credentials', ['integration_id'], unique=False)
    # ### end Alembic commands ###
