"""composite index of user_id and service

Revision ID: 2d0a61f83342
Revises: 440cb3a520be
Create Date: 2026-06-11 12:26:01.675995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0a61f83342'
down_revision: Union[str, Sequence[str], None] = '440cb3a520be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_integrations_service'), table_name='users_integrations')
    op.drop_index(op.f('ix_users_integrations_user_id'), table_name='users_integrations')
    op.create_index('idx_user_id_and_service', 'users_integrations', ['user_id', 'service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id_and_service', table_name='users_integrations')
    op.create_index(op.f('ix_users_integrations_user_id'), 'users_integrations', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_integrations_service'), 'users_integrations', ['service'], unique=False)
    # ### end Alembic commands ###
