"""added username field in users table bcz last was mistake

Revision ID: 2da70310313e
Revises: ebe658dc5d24
Create Date: 2026-06-10 15:10:42.880542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da70310313e'
down_revision: Union[str, Sequence[str], None] = 'ebe658dc5d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('oauth_accounts_username_key'), 'oauth_accounts', type_='unique')
    op.drop_column('oauth_accounts', 'username')
    op.add_column('users', sa.Column('username', sa.TEXT(), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.add_column('oauth_accounts', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('oauth_accounts_username_key'), 'oauth_accounts', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
