"""nodes registry in picture

Revision ID: 6cc2a6efd16f
Revises: 2da70310313e
Create Date: 2026-06-10 16:23:01.303775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cc2a6efd16f'
down_revision: Union[str, Sequence[str], None] = '2da70310313e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes_registry',
    sa.Column('fn_key', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('type', postgresql.ENUM('ACTION', 'LLM', 'TRANSFORM', 'API', 'DATA_SOURCE', 'CONTROL_FLOW', 'TRIGGER', name='nodes_type_enum'), nullable=False),
    sa.Column('service', sa.TEXT(), nullable=False),
    sa.Column('valid_permissions', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('input_model', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_model', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('fn_key')
    )
    op.create_index(op.f('ix_nodes_registry_service'), 'nodes_registry', ['service'], unique=False)
    op.create_index(op.f('ix_nodes_registry_type'), 'nodes_registry', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_registry_type'), table_name='nodes_registry')
    op.drop_index(op.f('ix_nodes_registry_service'), table_name='nodes_registry')
    op.drop_table('nodes_registry')
    # ### end Alembic commands ###
