"""nodes and edges to pg.ARRAY(pg.JSONB)

Revision ID: 7558fbd4acf7
Revises: 38ed925c9a02
Create Date: 2026-06-11 09:56:35.867990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7558fbd4acf7'
down_revision: Union[str, Sequence[str], None] = '38ed925c9a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
