"""scopes included in user_integrations table

Revision ID: a14fa9ed6e0d
Revises: 2d0a61f83342
Create Date: 2026-06-11 13:12:18.747722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a14fa9ed6e0d'
down_revision: Union[str, Sequence[str], None] = '2d0a61f83342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_integrations', sa.Column('scopes', postgresql.ARRAY(sa.TEXT()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_integrations', 'scopes')
    # ### end Alembic commands ###
