"""added username field in users table

Revision ID: ebe658dc5d24
Revises: dc3021a692a2
Create Date: 2026-06-10 14:58:24.550657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe658dc5d24'
down_revision: Union[str, Sequence[str], None] = 'dc3021a692a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('username', sa.TEXT(), nullable=False))
    op.create_unique_constraint(None, 'oauth_accounts', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_accounts', type_='unique')
    op.drop_column('oauth_accounts', 'username')
    # ### end Alembic commands ###
